<script type="text/javascript">

    var universe;

    $(function()
    {
        universe = new Universe('universe');

        $('#controls [name=resolution]').change(function(){
            universe.init();
        });

        $('button[name=create-noise]').click(function(e) {
            universe.createNoise()
        });
        $('button[name=next-frame]').click(function(e) {
            universe.nextFrame()
        });
        $('button[name=clear]').click(function(e) {
            universe.clear()
        });

        $('body').keyup(function(e) {
            if (e.which == 49)
            {
                $('button[name=create-noise]').trigger('click');
            }
            else if (e.which == 50)
            {
                $('button[name=next-frame]').trigger('click');
            }
            else if (e.which == 51)
            {
                $('button[name=clear]').trigger('click');
            }
        });
    });

</script>

<div id="universe">
    <div class="content">
        <h2>How to</h2>
        <ol>
            <li>
                Create noise: creates a random map of the early universe, also kown as the <a href="http://en.wikipedia.org/wiki/Cosmic_microwave_background_radiation" target="_blank">cosmic background radiation</a>.
            </li>
            <li>
                Next frame: pressing this button will compute  a simple <a href="http://en.wikipedia.org/wiki/Gravitational_field" target="_blank">gravitational field</a> for each particle on the map.<br>
                Every particle will then be moved according to the resulting forces of the fields.
            </li>
            <li>
                Repeat the last step to see how the universe is forming by the forces of gravity...<br>
            </li>
        </ol>

        <h3>Background</h3>
        <ul>
            <li>
                The simulation is done under heavy use of the HTML5 <a href="http://www.whatwg.org/specs/web-apps/current-work/multipage/the-canvas-element.html" target="_blank">canvas element</a> and <a href="http://www.whatwg.org/specs/web-apps/current-work/multipage/workers.html" target="_blank">web workers</a>.
            </li>
            <li>
                Browsers that do not support either one of those features will fail to run the simulation.
            </li>
            <li>
                Multithreading support is optimized for up to 8 cores using web workers.
            </li>
        </ul>

        <h3>Disclaimer</h3>
        <ul>
            <li>
                This simulation is by no means accurate.<br>
                Although the basic principles are correct and the resulting structures seem to be familiar.
            </li>
        </ul>
    </div>
</div>
<div id="controls">
    <div id="controls-actions">
        <button name="create-noise">1. Create noise</button>
        <button name="next-frame">2. Next frame</button>
        <button name="clear">3. Clear</button>
    </div>
    <div id="controls-options">
        <h3>Options</h3>
        <div class="content">
            <table>
                <tbody>
                <tr>
                    <td>Resolution:</td>
                    <td>
                        <select name="resolution">
                            <option value="high">high</option>
                            <option value="medium" selected="selected">medium</option>
                            <option value="low">low</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>Wrap edges:</td>
                    <td>
                        <input type="checkbox" name="wrap-edges" value="1" checked="checked">
                        (unchecking this option will cause mass to get lost on the boarders)
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div id="log">
        <h3>Log</h3>
        <div class="content">
        </div>
    </div>
</div>