<html>
<head>
    <?php echo $this->headLink()->appendStylesheet($this->baseUrl('css/style.css')); ?>
    <?php echo $this->headScript()->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js'); ?>
    <?php echo $this->headScript()->appendFile($this->baseUrl('js/kinetic-v4.0.1.min.js')); ?>
    <?php echo $this->headScript()->appendFile($this->baseUrl('js/perlin-noise-simplex.js')); ?>
    <?php echo $this->headScript()->appendFile($this->baseUrl('js/log.js')); ?>
    <?php echo $this->headScript()->appendFile($this->baseUrl('js/noise.js')); ?>
    <?php echo $this->headScript()->appendFile($this->baseUrl('js/universe.js')); ?>
</head>
<body>
    <?php echo $this->layout()->content; ?>
</body>
</html>