<?php echo $this->doctype() ?>

<html>
<head>
    <?php echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8'); ?>

    <?php echo $this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=Electrolize')
    ->appendStylesheet($this->baseUrl('css/style.css')); ?>

    <?php echo $this->headScript()->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js')
    ->appendFile($this->baseUrl('js/perlin-noise-simplex.js'))
    ->appendFile($this->baseUrl('js/log.js'))
    ->appendFile($this->baseUrl('js/noise.js'))
    ->appendFile($this->baseUrl('js/universe.js')); ?>
</head>
<body>
    <div id="wrapper">
        <header>
            <h1>createauniverse.net</h1>
        </header>
        <div id="content">
            <?php echo $this->layout()->content; ?>
        </div>
        <footer>
            <p><?php echo date('Y'); ?> by Raphael Stäbler</p>
        </footer>
    </div>
</body>
</html>